---
title: "Untitled"
author: "junseo"
date: "2018년 4월 13일"
output: html_document
---
```{r}
ca <- 1:10
 y <-c( 10.2, 13.71, 19.6, 23.5,25.6, 23.3,25.1,17.5,14.3,0.02)
lm(y~ca)
plot(ca,y,cex=2)
abline(20.466,-0.5787,col="red")
```
  
##다항회귀
```{r}
lm(y~ca+I(ca^2))

```
어떻게 곡선 그릴지 고민해보기  
x가 증가할 때 x^2도 같이 움직이니깐 해석은 동시에 해석  
```{r}
## 비선형 가변수 예제
y1<- c(2.5,1,3,1.5,2.5)
y2<- y1*2
y3 <- y1/2
y <- c(y1,rev(y2),rev(y3))
x <- 1:15
 
fx1 <- lm(y~x)
plot(x,y)
abline(fx1$coefficients)
 
fx2<- lm(y~I(x<=5)+I(x>5 & x<=10) + I(x>11))
fx2
```

```{r}
## 매출액 자료
y <- c(231.21,337.28,336.81,300.44,283.91,255.61,285.49,338.52,
238.37,259.98,280.13,306.02,224.70,264.45,317.51,327.78)
 
x <- rep(c("봄","여름","가을","겨울"),times=4)
 
# 1. 가변수 직접만들기
# 여름
z1 <- rep(0,16)
z1[c(2,6,10,14)] <- 1
 
# 가을
z2 <- rep(0,16)
z2[c(3,7,11,15)] <- 1
 
# 겨울
z3 <- rep(0,16)
z3[c(4,8,12,16)] <- 1

cbind(z1,z2,z3) 

# 2. factor 이용
factor(x) #level안주면 ㄱ,ㄴ,ㄷ순으로 설정된다
fx <- factor(x,levels = c("봄","여름","가을","겨울"))
lm(y~fx)
 
lfx <- relevel(fx,"봄")
lm(y~fx)

dat<-data.frame(y, x, z1, z2, z3)
lfit<-lm(y~z1+z2+z3, data = dat)
summary(lfit) 
```

